-- MySQL Script generated by MySQL Workbench
-- Fri May 27 16:22:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Schools
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Schools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Schools` DEFAULT CHARACTER SET utf8 ;
USE `Schools` ;

-- -----------------------------------------------------
-- Table `Schools`.`Types_School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schools`.`Types_School` (
  `IdTypeSchool_Pk` INT NOT NULL AUTO_INCREMENT,
  `NameTypeSchool` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdTypeSchool_Pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schools`.`Educational_Levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schools`.`Educational_Levels` (
  `IdEduLevel_Pk` INT NOT NULL AUTO_INCREMENT,
  `NameEduLevel` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdEduLevel_Pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schools`.`Municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schools`.`Municipalities` (
  `IdMuni_Pk` INT NOT NULL AUTO_INCREMENT,
  `MuniName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdMuni_Pk`),
  UNIQUE INDEX `MuniName_UNIQUE` (`MuniName` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schools`.`Schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schools`.`Schools` (
  `IdSchool_Pk` INT NOT NULL AUTO_INCREMENT,
  `SchoolCode` VARCHAR(35) NOT NULL,
  `NameSchool` VARCHAR(45) NOT NULL,
  `SchoolAddress` VARCHAR(55) NULL,
  `IdTypeSchool_S_Fk` INT NOT NULL,
  `IdEduLevel_S_Fk` INT NOT NULL,
  `IdMuni_S_Fk` INT NOT NULL,
  PRIMARY KEY (`IdSchool_Pk`),
  INDEX `IdEduLevel_S_Fk_idx` (`IdEduLevel_S_Fk` ASC) ,
  INDEX `IdTypeSchool_S_Fk_idx` (`IdTypeSchool_S_Fk` ASC) ,
  INDEX `IdMuni_S_Fk_idx` (`IdMuni_S_Fk` ASC) ,
  UNIQUE INDEX `SchoolCode_UNIQUE` (`SchoolCode` ASC) ,
  CONSTRAINT `IdEduLevel_S_Fk`
    FOREIGN KEY (`IdEduLevel_S_Fk`)
    REFERENCES `Schools`.`Educational_Levels` (`IdEduLevel_Pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdTypeSchool_S_Fk`
    FOREIGN KEY (`IdTypeSchool_S_Fk`)
    REFERENCES `Schools`.`Types_School` (`IdTypeSchool_Pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdMuni_S_Fk`
    FOREIGN KEY (`IdMuni_S_Fk`)
    REFERENCES `Schools`.`Municipalities` (`IdMuni_Pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
